### ISSUE TITLE
What to do with files, that do not encode night and run_id?

### ISSUE THREAD

**Issue by jebuss** [fact-project/read_mars#12]
https://github.com/fact-project/read_mars/blob/b3868d0abe9f99568f3218c1a5f81628c91ed8b8/read_mars/status_display.py#L36

**Comment by jebuss** [comment]
Now that I think about it: We should delete the date. The object called status_display does not have the  date and runid intrinsically. This is only sometime the case e.g. for single pe measurements.

https://github.com/fact-project/read_mars/blob/b3868d0abe9f99568f3218c1a5f81628c91ed8b8/read_mars/status_display.py#L36-L37

run and night shouldn't be members of statusdisplay

**Comment by dneise** [comment]
you are right.

**Comment by jebuss** [comment]
I opened a new issue for this and close this issue.
