### ISSUE TITLE
Delete run and date from StatusDisplay

### ISSUE THREAD

**Issue by jebuss** [fact-project/read_mars#13]
We should delete the date. The object called status_display does not have the  date and runid intrinsically. This is only sometime the case e.g. for single pe measurements.

https://github.com/fact-project/read_mars/blob/b3868d0abe9f99568f3218c1a5f81628c91ed8b8/read_mars/status_display.py#L36-L37

run and night shouldn't be members of statusdisplay

**Comment by dneise** [comment]
I think, when we delete date and run, then the function has nearly no reason anymore to take a path, right? It could immediately take a TFile object ... maybe this is cleaner ... maybe not. 

https://github.com/fact-project/read_mars/blob/b3868d0abe9f99568f3218c1a5f81628c91ed8b8/read_mars/status_display.py#L34-L39

this is the only part of the function, where `self.path` is used.

**Comment by dneise** [comment]
But maybe giving it a path is more convenient or so, dunno.

**Comment by jebuss** [comment]
Yes, I think giving a path is more convenient. Id like to hide the entire root BS from the user

**Comment by dneise** [comment]
agreed
